### ISSUE TITLE
Slack link expired

### ISSUE THREAD

**Issue by chyla** [rocky-linux/rocky#75] opened 2020-12-14 12:52 UTC
Hi,

Slack link expired, could you update it?

**Comment by hbjydev** [comment] 2020-12-14 13:18
@NeilHanlon What's the status on the auto-invite system?

**Comment by hbjydev** [comment] 2020-12-14 13:19
Closing, duplicate of #63

**Closed by hbjydev** 2020-12-14 13:19 UTC

**Comment by NeilHanlon** [comment] 2020-12-14 13:23
> @NeilHanlon What's the status on the auto-invite system?

Will dm you
